name: Rest Contract CI/CD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    name: build_and_test
    uses: ./.github/workflows/rest_contract_cicd.yaml
    with:
      schema_name: contract-rest-questionnaire
      publish: ${{ github.ref == 'refs/heads/main' }}
    secrets:
      nexus_user:      ${{ secrets.NEXUS_RAW_USER }}
      nexus_token:     ${{ secrets.NEXUS_RAW_TOKEN }}
