name: Rest Contract CI/CD

on:
  workflow_call:
    inputs:
      publish:
        required: false
        default: false
        type: boolean
    secrets:
      nexus_user:
        required: false
      nexus_token:
        required: false

jobs:
  cicd:
    name: Pull Request CI/CD flow
    runs-on: self-hosted
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.1.0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "zulu"

      - name: Run Tests
        id: run_tests
        run: ./gradlew check

      - name: Compile Schemas
        id: compile_schemas
        run: ./gradlew build

      - name: Publish Artifact
        if: ${{ inputs.publish }}
        id: publish_artifact
        run: ./gradlew assemble publish
        env:
          NEXUS_USER: ${{ secrets.NEXUS_MAVEN_USER }}
          NEXUS_TOKEN: ${{ secrets.NEXUS_MAVEN_TOKEN }}
